name: 打包应用并上传腾讯云

on:
  push:
    branches:
      - main

jobs:
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: 迁出代码
        # 使用action库  actions/checkout获取源码
        uses: actions/checkout@main
      # 安装Node10

      - name: 安装node.js
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 14.0.0

      # 安装依赖
      - name: 安装依赖
        run: npm install

      # 打包
      - name: 打包
        run: npm run build

      # 上传腾讯云
      - name: 发布到腾讯云
        uses: appleboy/ssh-action@master
        env:
          with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
